services:

  nginx:
    build: ./nginx
    image: nginx:oo
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - trance
    init: true

  user:
    build: ./user
    image: user:oo
    container_name: user
    ports:
      - "3000:3000"
    networks:
      - trance
    init: true

  auth:
    build: ./auth
    image: auth:oo
    container_name: auth
    ports:
      - "3001:3001"
    networks:
      - trance
    init: true

  redis:
    build: ./redis
    image: redis:oo
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - trance
    init: true

networks:
  trance:
